version: '3.8'

services:
  kafka:
    image: apache/kafka:latest
    container_name: kafka
    ports:
      - "9092:9092"


    environment:
      KAFKA_NODE_ID: 1
      CLUSTER_ID: 'MkU3OEVBNTcwNTg0NDM0Qk'
      KAFKA_PROCESS_ROLES: 'broker,controller'
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@kafka:9093'
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LOG_DIRS: /tmp/kraft-combined-logs

    volumes:
      - ./data:/tmp/kraft-combined-logs



  kafka-init:
    image: apache/kafka:latest
    container_name: kafka-init
    depends_on:
      - kafka
    network_mode: "service:kafka"
    entrypoint:
      - /bin/bash
      - -c
      - |
        echo "Waiting for Kafka..."
        sleep 15

        echo "Creating topic: witsml-drilling-data"

        /opt/kafka/bin/kafka-topics.sh \
          --bootstrap-server localhost:9092 \
          --create \
          --if-not-exists \
          --topic witsml-drilling-data \
          --partitions 1 \
          --replication-factor 1

        echo "Topic creation finished."

        echo "Current topics:"
        /opt/kafka/bin/kafka-topics.sh \
          --bootstrap-server localhost:9092 \
          --list